app/build.gradle.kts, app/src/androidTest/java/com/github/se/assocify/screens/ReceiptScreenTest.kt, app/src/main/java/com/github/se/assocify/navigation/Destination.kt, app/src/main/java/com/github/se/assocify/navigation/NavigationActions.kt, app/src/main/java/com/github/se/assocify/ui/composables/DatePickerWithDialog.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/receipt/ReceiptScreen.kt, app/src/test/java/com/github/se/assocify/navigation/NavigationActionsTest.kt
=> Receipt UI

app/src/androidTest/java/com/github/se/assocify/screens/CreateAssoScreenTest.kt, app/src/main/java/com/github/se/assocify/ui/screens/createAsso/CreateAssoScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/createAsso/CreateAssoViewmodel.kt, app/src/main/java/com/github/se/assocify/ui/screens/createAsso/createAssoScreen.kt, app/src/main/res/drawable/landscape.xml
Connected to user story #32 and issue #22 
The UI of the "create a new association" page, where a committee member of an association can register it on the app : with the association's name, logo, and members. Members are users already registered in the app, with their name and picture. They will be assigned a role within the association which will give them different permissions on the app.
=> UI - Create new association page

app/build.gradle.kts, app/src/androidTest/java/com/github/se/assocify/AssociationAPITest.kt, app/src/androidTest/java/com/github/se/assocify/AssociationUtilsTest.kt, app/src/androidTest/java/com/github/se/assocify/FirebaseTest.kt, app/src/androidTest/java/com/github/se/assocify/UserAPITest.kt, app/src/androidTest/java/com/github/se/assocify/screens/SelectAssociationScreenTest.kt, app/src/main/java/com/github/se/assocify/model/associations/AssociationUtils.kt, app/src/main/java/com/github/se/assocify/model/entities/Association.kt, app/src/main/java/com/github/se/assocify/model/entities/Event.kt, app/src/main/java/com/github/se/assocify/model/entities/Role.kt, app/src/main/java/com/github/se/assocify/model/entities/User.kt, app/src/main/java/com/github/se/assocify/ui/screens/createAsso/CreateAssoScreen.kt, app/src/test/java/com/github/se/assocify/navigation/NavigationActionsTest.kt, app/src/test/java/com/github/se/assocify/navigation/model/entities/AssociationTest.kt, app/src/test/java/com/github/se/assocify/navigation/model/entities/EventTest.kt, app/src/test/java/com/github/se/assocify/navigation/model/entities/RoleTest.kt, app/src/test/java/com/github/se/assocify/navigation/model/entities/UserTest.kt
I added some basic methods to all entities including :
I also put the main attributes of entities in private to force going by the getters for better maintanability and reduce developer mistakes.
=> Add basic Entity methods and tests for maintanability

.github/workflows/apk-build.yml, .github/workflows/ci.yml, .gitignore, app/build.gradle.kts
"You must set up your repo with a GitHub workflow to build the app's APK such that, at the end of every Sprint, you can create a new release at the push of a button." - M1
This sets that up.
=> ci: add building APK

app/src/androidTest/java/com/github/se/assocify/screens/ReceiptScreenTest.kt, app/src/main/java/com/github/se/assocify/model/database/ReceiptAPI.kt, app/src/main/java/com/github/se/assocify/navigation/Destination.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/ReceiptListViewModel.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/receipt/ReceiptGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/receipt/ReceiptScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/receipt/ReceiptViewModel.kt, app/src/main/java/com/github/se/assocify/ui/util/PriceUtil.kt, app/src/test/java/com/github/se/assocify/model/database/ReceiptsAPITest.kt, app/src/test/java/com/github/se/assocify/utils/PriceUtilTest.kt
Makes sure the following actions work : 
Also some minor visual cleanup, and refactors ReceiptAPI
=> Receipt Navigation

app/src/main/java/com/github/se/assocify/ui/screens/login/LoginViewModel.kt
There was a problem when entering the treasury page because the association uid was set to an empty string. Since we don't have the relation between a user and multiple association, we can't fetch properly the associationuid from the db. I added another issue for later, when the relations will be implemented to fetch the association uid accordingly.
=> Set association uid to non empty string

app/src/androidTest/java/com/github/se/assocify/screens/AccountingScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/BalanceDetailedScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/BudgetDetailedScreenTest.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingScreen.kt
In Budget and balance sheet and budget and balance detailed sheet, the filter row wasn't scrollable. Thus, the filter chips weren't well displayed.
=> Scrollable filter row

app/src/main/java/com/github/se/assocify/model/database/TaskAPI.kt, app/src/main/java/com/github/se/assocify/model/entities/Task.kt, app/src/test/java/com/github/se/assocify/model/database/TaskAPITest.kt
Even if the tests of Task API passed, the database had problems detecting the Time format used locally. Thus I decided to modify the Task value so that it now uses a LocalDateTime which will make it easier to use it.
=> Repair Task API

app/src/main/java/com/github/se/assocify/model/database/UserAPI.kt, app/src/test/java/com/github/se/assocify/model/database/UserAPITest.kt
This adds a way to get the current user's role in the current association. It is not very efficient, but we will add caching soon.
=> Add a get for the current user's role in the current association

app/src/androidTest/java/com/github/se/assocify/screens/BalanceDetailedScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/BudgetDetailedScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/CreateAssoScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/LoginTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/ReceiptScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/SelectAssociationScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/TreasuryScreenTest.kt, app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/login/LoginGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/login/LoginScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/selectAssociation/SelectAssociationGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/selectAssociation/SelectAssociationScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/balance/BalanceDetailedGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/balance/BalanceDetailedScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetDetailedGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetDetailedScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptViewModel.kt
When refreshing, some pages were sending a new request to the database each time because the viewmodel was entirely recomposed. To avoid this, I'm creating the viewmodels outside of the screen and passing it as argument, everywhere where this wasn't already the case
=> BugFix: Multiple Reload

app/src/androidTest/java/com/github/se/assocify/Epic4Test.kt, app/src/androidTest/java/com/github/se/assocify/EpicPrezTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/SelectAssociationScreenTest.kt, app/src/main/java/com/github/se/assocify/navigation/NavigationActions.kt, app/src/main/java/com/github/se/assocify/ui/composables/DropdownWithSetOptions.kt, app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationViewmodel.kt, app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileViewModel.kt, app/src/main/java/com/github/se/assocify/ui/screens/selectAssociation/SelectAssociationGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/selectAssociation/SelectAssociationScreen.kt, app/src/test/java/com/github/se/assocify/navigation/NavigationActionsTest.kt
Currently, the only way to join an association is when you first register in the app and if someone else adds you in their association when creating it. The goal of this PR is to add a way to join another association, from the profile.
=> Profile : add the option to join another association

app/src/androidTest/java/com/github/se/assocify/Epic1Test.kt, app/src/androidTest/java/com/github/se/assocify/screens/AccountingScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/BalanceDetailedScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/BudgetDetailedScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/TreasuryScreenTest.kt, app/src/main/java/com/github/se/assocify/AssocifyApp.kt, app/src/main/java/com/github/se/assocify/model/database/AccountingSubCategoryAPI.kt, app/src/main/java/com/github/se/assocify/model/database/BudgetAPI.kt, app/src/main/java/com/github/se/assocify/model/entities/AccountingCategory.kt, app/src/main/java/com/github/se/assocify/model/entities/AccountingSubCategory.kt, app/src/main/java/com/github/se/assocify/navigation/NavigationGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryGraph.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetViewModel.kt, app/src/test/java/com/github/se/assocify/model/database/AccountingSubCategoryTest.kt, app/src/test/java/com/github/se/assocify/model/database/BudgetAPITest.kt
Missing filter by year and VTA
This PR will be pushed in ft/AccountingAPI0, because both branches have dependent code.
I closed PR #246 which indicated that I did some code that I didn't do.
=> Implementation of BudgetViewModel

app/src/main/java/com/github/se/assocify/model/database/AccountingSubCategoryAPI.kt
PATCH : the last PR that wasn't functional.
Now in the DB it is possible to edit the categoryUID of a subcategory.
=> Allow to move subcategories between categories in DB

app/src/main/java/com/github/se/assocify/model/database/ReceiptAPI.kt, app/src/test/java/com/github/se/assocify/model/database/ReceiptsAPITest.kt
Adds receipt caching, as well as a method to update the caches (i.e. refresh the lists).
The cache is split into two parts, the user receipts and the global receipts.
Completes part of #206.
=> Receipt caching

app/src/androidTest/java/com/github/se/assocify/screens/AccountingScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/BalanceDetailedScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/BudgetDetailedScreenTest.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingViewModel.kt, app/src/main/java/com/github/se/assocify/ui/util/DateUtil.kt
The treasury page contains some problems, which are the fact that the year list is harcoded and the year filter does not work on the overview screen. The objective of this PR is to fix these two linked problems so that the utilization of time in the tresury tab becomes finally correct
=> Fix time problems on the treasury page

app/src/main/java/com/github/se/assocify/AssocifyApp.kt, app/src/main/java/com/github/se/assocify/model/database/AccountingCategoryAPI.kt, app/src/main/java/com/github/se/assocify/model/database/AccountingSubCategoryAPI.kt, app/src/test/java/com/github/se/assocify/model/database/AccountingCategoryAPITest.kt, app/src/test/java/com/github/se/assocify/model/database/AccountingSubCategoryTest.kt
Completes part of https://github.com/Assocify-Team/Assocify/issues/206.
This PR adds caching to the AccountCategoryAPI and AccountSubcategoryAPI. Similarly to other caching PRs, it allows manual refreshing, but not automatic.
=> Category and subcategory caching

app/src/main/java/com/github/se/assocify/model/database/UserAPI.kt, app/src/test/java/com/github/se/assocify/model/database/UserAPITest.kt
Completes part of https://github.com/Assocify-Team/Assocify/issues/206.
This PR adds caching to the User API. This makes the profile page and association creation page load faster. The cache needs to be manually refreshed to receive outside updates, but it does not need to be updated manually after local changes.
Tests have not been added, but depending on current coverage I will add some.
=> User API caching

app/src/main/java/com/github/se/assocify/model/database/EventAPI.kt, app/src/test/java/com/github/se/assocify/model/database/EventAPITest.kt
Completes part of https://github.com/Assocify-Team/Assocify/issues/206.
This PR adds caching to the Event API. The cache needs to be manually refreshed to receive outside updates, but it does not need to be updated manually after local changes.
It also replaces all the `scope.launch`es with `tryAsync`, for consistency.
Tests have not been added, but depending on current coverage I will add some.
=> Event API caching

app/src/main/java/com/github/se/assocify/ui/composables/UserSearchTextField.kt, app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/event/tasktab/task/TaskScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/newcategory/AddCategoryScreen.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptScreen.kt
Closes #331
Previously, many text entries were multi-line. This made it possible to have multi-line names, which look strange and might break the UI. This fixes that. It is local-only, but because it only causes visual glitches, it's okay that it's not in the database.
=> Make text entries single line

app/src/main/java/com/github/se/assocify/model/database/TaskAPI.kt
Task api wasn't updating the cache when deleting a task. Now it is updated :)
=> Fix Task API cache

app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
There is a little problem: the TVA on the single values is not activated when the filter of TVA is activated. The objective of this PR is to fix this single issue so it can be repaired and the TVA can be consistent everywhere.
=> Fix the TVA issues on single item

.github/workflows/apk-build.yml
We forgot to fix the CI after M2. This PR brings that fix to the main branch. It only fixes the APK generation CI, because the testing CI doesn't need to have access to the actual database, and so it is ensured.
=> Repair APK CI

app/src/androidTest/java/com/github/se/assocify/screens/BalanceDetailedScreenTest.kt, app/src/androidTest/java/com/github/se/assocify/screens/ReceiptScreenTest.kt, app/src/main/java/com/github/se/assocify/model/database/ReceiptAPI.kt, app/src/main/java/com/github/se/assocify/model/entities/Receipt.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptViewModel.kt, app/src/test/java/com/github/se/assocify/model/database/ReceiptsAPITest.kt
Closes #306.
This PR adds a `userId` field to `Receipt`, which already existed in the database but was simply not linked. This PR also makes editing receipts not transfer their owner.
=> Add receipt owners to receipt entity

app/src/main/java/com/github/se/assocify/model/database/ReceiptAPI.kt
This PR focuses on the synchronization of the current association and the displayed receipts.
Now you can only display the receipts from the association you're in :)
=> Link receipts to the current association

app/src/main/java/com/github/se/assocify/model/database/EventAPI.kt
Changing associations now change the events you're seeing in real-time, not only at the beginning of the app.
=> Link event to asso

app/src/androidTest/java/com/github/se/assocify/Epic1Test.kt, app/src/androidTest/java/com/github/se/assocify/Epic4Test.kt, app/src/androidTest/java/com/github/se/assocify/screens/profile/ProfileScreenTest.kt, app/src/main/java/com/github/se/assocify/model/database/ImageCacher.kt, app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileViewModel.kt
Closes #262. This PR adds the ability to add and load profile pictures. If the image cannot be fetched, the default icon is displayed and an error is shown, but the page still loads, because it is not a core functionality.
Still needs to be done: refresh the profile picture on reload.
=> Profile pictures for users

app/src/androidTest/java/com/github/se/assocify/screens/BudgetDetailedScreenTest.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetDetailedViewModel.kt, app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt
This PR enables the fact that amount in budgets can be negative. Of course, you can budget an expense... There was just a check in the viiewmodel that I removed.
=> Bug fix: amount in budget can be negative

app/src/main/java/com/github/se/assocify/model/database/UserAPI.kt, app/src/test/java/com/github/se/assocify/model/database/UserAPITest.kt
Added the possibility to remove the user from an association.
Added the possibility to change the role of a user in an association.
Enjoy :)))
=> Methods for managing Association Members

app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreen.kt
Because the component for tab change, a bug re-appeared. When on the map tab, sliding left/right was sliding tab instead of sliding on the map which is very annoying for user experience.
This PR addresses #413
=> Fix map right/left slide
