Assocify-Team/Assocify

.commitlintrc.json
.github/workflows/conventional-commits.yml
.husky/commit-msg
.husky/pre-commit
package-lock.json
package.json

Adds a Git hook and CI for checking commit names. See [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
Uses [config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional)

Commit Lint 

---

app/src/androidTest/java/com/github/se/assocify/FirebaseTest.kt

Fixed firebase test to await the result of Database

fix: firebasetest await for result

---

app/build.gradle.kts

Passes tests locally.
Closes #20.

chore: update dependencies

---

app/src/main/java/com/github/se/assocify/model/database/FirebaseAPI.kt

feat: created basic firebase API

---

app/build.gradle.kts
app/src/androidTest/java/com/github/se/assocify/AssociationAPITest.kt
app/src/androidTest/java/com/github/se/assocify/FirebaseTest.kt
app/src/androidTest/java/com/github/se/assocify/UserAPITest.kt
app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
app/src/main/java/com/github/se/assocify/model/database/FirebaseAPI.kt
app/src/main/java/com/github/se/assocify/model/database/UserAPI.kt

Association API :
User API :
Tests :

Association API, User API

---

app/src/androidTest/java/com/github/se/assocify/AssociationAPITest.kt
app/src/androidTest/java/com/github/se/assocify/AssociationUtilsTest.kt
app/src/androidTest/java/com/github/se/assocify/FirebaseTest.kt
app/src/androidTest/java/com/github/se/assocify/UserAPITest.kt
app/src/main/java/com/github/se/assocify/model/associations/AssociationUtils.kt
app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
app/src/main/java/com/github/se/assocify/model/database/FirebaseAPI.kt
app/src/main/java/com/github/se/assocify/model/database/UserAPI.kt

There was a problem caused the application to crash when the APIs were called. 
The fix is here, i implemented callback functions and adapted the tests.

Fix APIs Await problem 

---

app/src/main/java/com/github/se/assocify/model/entities/Role.kt
app/src/test/java/com/github/se/assocify/navigation/model/entities/RoleTest.kt

Adding an enum "RoleTypes" in the Role entities to have a list of all roles currently possible

Add enum for roles

---

app/src/main/java/com/github/se/assocify/model/database/ReceiptsAPI.kt
app/src/test/java/com/github/se/assocify/model/database/ReceiptsAPITest.kt

Adds single-receipt get, as well as deletion.

feat: Add more features to the Receipt API

---

app/build.gradle.kts
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

Organise, remove and update dependencies as needed

Dependencies

---

app/src/main/java/com/github/se/assocify/model/entities/Role.kt
app/src/test/java/com/github/se/assocify/model/entities/RoleTest.kt

Implementing Is an Active Role Function for maintanability.

Is an Active Role Function

---

app/src/androidTest/java/com/github/se/assocify/screens/EventScreenTest.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt

This PR simply adds animation when you switch between the tabs of the Event page.

Added animation to events tab

---

app/src/androidTest/java/com/github/se/assocify/screens/ProfileScreenTest.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileScreen.kt

Basic UI for the profile page : see Figma and linked issue #28

Create profile page UI

---

app/src/androidTest/java/com/github/se/assocify/screens/CreateAssoScreenTest.kt
app/src/main/java/com/github/se/assocify/model/entities/User.kt
app/src/main/java/com/github/se/assocify/ui/composables/UserSearchTextField.kt
app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationViewmodel.kt
app/src/main/java/com/github/se/assocify/ui/screens/selectAssociation/SelectAssociationScreen.kt
app/src/test/java/com/github/se/assocify/navigation/model/entities/UserTest.kt

Change the entity User back to having public values and no getters

Bugfix : change user to have no getters

---

app/src/androidTest/java/com/github/se/assocify/screens/AccountingScreenTest.kt
app/src/androidTest/java/com/github/se/assocify/screens/ReceiptScreenTest.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryGraph.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/balance/BalanceScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/ReceiptListScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/ReceiptListViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptGraph.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptViewModel.kt

Cleanup the Treasury Tab: extract necessary composables into seperate files, fix layout issues, fix scroll issues, refactor names to match convention, clean up minor UI issues

Cleanup Treasury Tab

---

app/src/androidTest/java/com/github/se/assocify/screens/profile/ProfileMembersScreenTest.kt
app/src/androidTest/java/com/github/se/assocify/screens/profile/ProfileRolesScreenTest.kt
app/src/androidTest/java/com/github/se/assocify/screens/profile/ProfileScreenTest.kt
app/src/main/java/com/github/se/assocify/navigation/Destination.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileGraph.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/members/ProfileMembersGraph.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/members/ProfileMembersScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/roles/ProfileRolesGraph.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/roles/ProfileRolesScreen.kt

Viewmodel for profile page : navigation to association settings

---

app/src/androidTest/java/com/github/se/assocify/screens/EventScreenTest.kt
app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
app/src/main/java/com/github/se/assocify/model/database/EventAPI.kt
app/src/main/java/com/github/se/assocify/model/entities/Event.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreenViewModel.kt
app/src/test/java/com/github/se/assocify/model/database/EventAPITest.kt

By implementing the Task screen I noticed that the event API does not work. The goal of this class is to standardize the Event class and make it work

Fix the EventAPI

---

app/src/androidTest/java/com/github/se/assocify/screens/AccountingScreenTest.kt
app/src/androidTest/java/com/github/se/assocify/screens/TreasuryScreenTest.kt
app/src/main/java/com/github/se/assocify/model/CurrentUser.kt
app/src/main/java/com/github/se/assocify/ui/composables/MainTopBar.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/ReceiptListViewModel.kt

Receipt Search Bar

---

app/src/androidTest/java/com/github/se/assocify/screens/BudgetDetailedScreenTest.kt
app/src/main/java/com/github/se/assocify/model/database/BudgetAPI.kt
app/src/main/java/com/github/se/assocify/model/entities/BalanceItem.kt
app/src/main/java/com/github/se/assocify/model/entities/BudgetItem.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingDetailedScreen.kt
app/src/test/java/com/github/se/assocify/model/database/BudgetAPITest.kt

Budget api

---

app/src/androidTest/java/com/github/se/assocify/screens/CreateAssoScreenTest.kt
app/src/androidTest/java/com/github/se/assocify/screens/profile/ProfileScreenTest.kt
app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
app/src/main/java/com/github/se/assocify/model/database/SupabaseObjects.kt
app/src/main/java/com/github/se/assocify/model/database/TaskAPI.kt
app/src/main/java/com/github/se/assocify/model/database/UserAPI.kt
app/src/main/java/com/github/se/assocify/model/entities/Role.kt
app/src/main/java/com/github/se/assocify/model/entities/User.kt
app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationViewmodel.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileViewModel.kt
app/src/test/java/com/github/se/assocify/model/database/APITestUtils.kt
app/src/test/java/com/github/se/assocify/model/database/AssociationAPITest.kt
app/src/test/java/com/github/se/assocify/model/database/TaskAPITest.kt
app/src/test/java/com/github/se/assocify/model/database/UserAPITest.kt

Closes #190.
Implements roles. Still needs to be done:
Edit: the above has been moved to another issue, as this PR would become too large if this was added.

Implement roles

---

app/src/androidTest/java/com/github/se/assocify/screens/ReceiptScreenTest.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/ReceiptListViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptViewModel.kt

Fix: edit receipt from other user

---

app/src/main/java/com/github/se/assocify/ui/screens/event/tasktab/EventTaskScreen.kt
app/src/main/java/com/github/se/assocify/ui/util/TimeUtil.kt

I forgot to put the date to a more readable format in the task screen. Now I will try modifying it to have it look better.

Modify display time

---

app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
app/src/main/java/com/github/se/assocify/model/database/UserAPI.kt
app/src/main/java/com/github/se/assocify/ui/screens/selectAssociation/SelectAssociationViewModel.kt
app/src/test/java/com/github/se/assocify/model/database/AssociationAPITest.kt
app/src/test/java/com/github/se/assocify/model/database/UserAPITest.kt

This is a temporary (v1) stopgap for #196.
It automatically accepts invitations and requests. It has been tested manually, and includes doc comments.

Automatically accept invitations

---

app/src/main/java/com/github/se/assocify/ui/composables/InnerTabRow.kt
app/src/main/java/com/github/se/assocify/ui/composables/MainTopBar.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreenViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryViewModel.kt

Tab and Top Bar Structure

---

app/src/main/java/com/github/se/assocify/ui/composables/TimePickerWithDialog.kt
app/src/main/java/com/github/se/assocify/ui/composables/UserSearchTextField.kt
app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationViewmodel.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/tasktab/task/TaskScreen.kt

Reduce the complexity of the code

Reduce Complexity

---

app/src/androidTest/java/com/github/se/assocify/screens/ScheduleScreenTest.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/scheduletab/EventScheduleScreen.kt

Schedule UI

---

app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
app/src/main/java/com/github/se/assocify/model/database/SupabaseApi.kt
app/src/test/java/com/github/se/assocify/model/database/AssociationAPITest.kt

The first caching PR. Part of #206. Quite basic caching, as associations are not queried very much.

Caching for AssociationAPI

---

app/src/main/java/com/github/se/assocify/model/database/SupabaseApi.kt
app/src/main/java/com/github/se/assocify/model/database/UserPreferenceAPI.kt
app/src/main/java/com/github/se/assocify/model/entities/UserPreference.kt
app/src/test/java/com/github/se/assocify/model/database/UserPreferenceAPITest.kt

**Store user parameters in the database.**
Created 3 files : 
- **Entity** : UserPreference
- **API** : UserPreferenceAPI
- **Test** : UserPreferenceAPITest
The parameters/User_Preferences include : 
- **Theme** : Dark, Light or System
- **Text size** : Int
- **Language** : English

User preferences and Parameters

---

app/src/main/java/com/github/se/assocify/model/database/AccountingSubCategoryAPI.kt
app/src/test/java/com/github/se/assocify/model/database/AccountingSubCategoryTest.kt

Allow to modify the category of an item

Minor fix : modify the category of an item

---

app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/selectAssociation/SelectAssociationViewModel.kt

Minor fixes in the navigation from selectAsso when joining and with the list of displayed associations in profile after that

Bugfix : Profile and join asso

---

app/src/androidTest/java/com/github/se/assocify/screens/ScheduleScreenTest.kt
app/src/main/java/com/github/se/assocify/ui/composables/DatePickerWithDialog.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventGraph.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreenViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/scheduletab/EventScheduleScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/scheduletab/EventScheduleViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/tasktab/EventTaskScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/tasktab/task/TaskViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/ReceiptListScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptViewModel.kt
app/src/main/java/com/github/se/assocify/ui/util/DateTimeUtil.kt
app/src/main/java/com/github/se/assocify/ui/util/DateUtil.kt
app/src/main/java/com/github/se/assocify/ui/util/TimeUtil.kt
app/src/test/java/com/github/se/assocify/utils/TimeUtilTest.kt

Schedule ViewModel

---

app/src/androidTest/java/com/github/se/assocify/screens/TreasuryScreenTest.kt
app/src/main/java/com/github/se/assocify/ui/composables/MainTopBar.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryGraph.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingViewModel.kt

This PR implements the search of subcategories. Plus, I modified the accountingViewmodel so that we fetch only once the list of subcategory, and use the resulting local list to filter.

Search categories

---

app/src/androidTest/java/com/github/se/assocify/screens/CreateAssoScreenTest.kt
app/src/androidTest/java/com/github/se/assocify/screens/SelectAssociationScreenTest.kt
app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
app/src/main/java/com/github/se/assocify/ui/screens/createAssociation/CreateAssociationViewmodel.kt
app/src/main/java/com/github/se/assocify/ui/screens/selectAssociation/SelectAssociationViewModel.kt

Currently there's a problem when joining an association because we're trying to get the information from the cache except it's not yet in the cache since we're just joining...

BugFix : cache problem when joining asso

---

LICENSE

The GNU General Public License version 3 (GPLv3) is a free software license that ensures users have the freedom to run, study, share, and modify the software. Here's a simple breakdown of its key points:
Freedom to Use: You can use the software for any purpose without restrictions.
Access to Source Code: You have the right to access the software's source code, which allows you to study how it works and modify it.
Freedom to Share: You can redistribute copies of the software to others, either in its original form or with your modifications.
Share Alike: If you distribute modified versions of the software, you must also distribute the source code and keep it under the same GPLv3 license. This ensures that future users also have the same freedoms.
Protection Against Tivoization: GPLv3 …

Add a license to the project 

---

app/src/androidTest/java/com/github/se/assocify/screens/AddCategoryScreenTest.kt
app/src/androidTest/java/com/github/se/assocify/screens/AddSubcategoryDialogTest.kt
app/src/main/java/com/github/se/assocify/ui/composables/DropdownWithSetOptions.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/TreasuryScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/AccountingViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/accountingComposables/AddSubcategoryDialog.kt

Add the functionnality of the creating a subcategory dialog. Complete with some input conditions and error messages

Subcategory Viewmodel

---

app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/balance/BalanceDetailedViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/balance/BalancePopUpScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetDetailedViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/budget/BudgetPopUpScreen.kt

There were some problems remaining in some screens. This PR is to address those problems and correct functionality issues.

Repair some errors that remain

---

app/src/androidTest/java/com/github/se/assocify/screens/ReceiptScreenTest.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/receiptstab/receipt/ReceiptViewModel.kt
app/src/main/java/com/github/se/assocify/ui/util/SnackbarSystem.kt

Adds a class to easily call snackbars as needed in a more condensed and clean way.
I added them to the profile page, and the create/edit receipt page, for testing and review purposes. The rest will be done seperately.

Snackbar Gestionnaire

---

app/src/main/java/com/github/se/assocify/model/database/EventAPI.kt
app/src/test/java/com/github/se/assocify/model/database/EventAPITest.kt

Events and Associations are now linked in the database leading associations to see only the events they created ! :)

Link Event to Association

---

app/src/androidTest/java/com/github/se/assocify/screens/BalanceDetailedScreenTest.kt
app/src/main/java/com/github/se/assocify/model/database/BalanceAPI.kt
app/src/main/java/com/github/se/assocify/model/entities/BalanceItem.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreenViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/balance/BalanceDetailedViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/treasury/accounting/balance/BalancePopUpScreen.kt

Bugfixes for creating or editing a balance item

Balance Bugfix

---

app/src/androidTest/java/com/github/se/assocify/screens/EventScreenTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/maptab/EventMapScreen.kt

The PR adds a little character on the GPS location of the user. 
NB : only testable on phone. Can be tested on emulator by using location settings of it but the emulator isn't really good at simulating GPS.
This PR addresses #326.

Added GPS location on the map

---

app/src/main/java/com/github/se/assocify/model/database/AssociationAPI.kt
app/src/main/java/com/github/se/assocify/model/database/ReceiptAPI.kt
app/src/main/java/com/github/se/assocify/ui/composables/MainTopBar.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/EventScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/event/scheduletab/EventScheduleScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/ProfileViewModel.kt
app/src/main/java/com/github/se/assocify/ui/screens/profile/members/ProfileMembersScreen.kt
app/src/main/java/com/github/se/assocify/ui/screens/selectAssociation/SelectAssociationViewModel.kt
app/src/main/res/xml/data_extraction_rules.xml

We had the bad practice of leaving todos in the middle of the code. Now it's too late to keep them so we decided to remove them.

Remove all todos
